markdown: kramdown
relative_permalinks: false
url: http://chengjun.github.io
author: Cheng-Jun Wang
highlighter: rouge
permalink: /:year/:month/:title/
paginate: 10
paginate_path: "page:num"
safe: true
auto: true
